# Generated by Django 6.0 on 2026-01-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qno', models.IntegerField()),
                ('qname', models.CharField(max_length=20)),
                ('op1', models.CharField(max_length=20)),
                ('op2', models.CharField(max_length=20)),
                ('op3', models.CharField(max_length=20)),
                ('op4', models.CharField(max_length=20)),
                ('correct_ans', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('created_que', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('smob_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.student')),
            ],
        ),
    ]
