# Generated by Django 6.0 on 2026-01-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0006_alter_result_rid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='created_que',
        ),
    ]
