# Generated by Django 6.0 on 2026-01-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0008_rename_student_result_sname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
