# Generated by Django 6.0 on 2026-01-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0009_alter_student_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
